#1、配置4个pods  2、配置节点亲和性 不到控制节点 3、配置容器

apiVersion: apps/v1 # API版本，Deployment属于apps组的v1版本(固定不变，是给k8s看的)
kind: Deployment # 资源类型，这里声明这是一个Deployment
metadata:
  name: webdemo-deployment
spec:
  replicas: 4  # 总副本数：2 个节点 × 2 个 Pod
  selector:
    matchLabels: #selector用于定义 Deployment 要管理哪些 Pod：只有标签为app: webdemo的 Pod 会被这个 Deployment 控制
      app: webdemo
  template:
    metadata:
      labels:
        app: webdemo # Pod的标签，需与上面的selector.matchLabels一致
    spec:  # Pod的具体配置
      # 亲和性配置 确保 Pod 只调度到 worker 节点（排除控制平面）
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane  #控制节点自带的key
                    operator: DoesNotExist  # 不调度到控制平面节点
      containers:
        - name: webdemo
          image: webdemo:v1.0  # 你的 Spring Boot 镜像
          ports:
            - containerPort: 8080  # 容器内端口（与 Spring Boot 的 server.port 一致）
          resources:
            requests:
              cpu: "100m"  # 最小 CPU 需求
              memory: "256Mi"  # 最小内存需求

